"""initial_schema

Revision ID: 39b69cb487e2
Revises:
Create Date: 2026-03-07 19:02:34.354838
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "39b69cb487e2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column("input_text", sa.Text(), nullable=True),
        sa.Column("style", sa.String(length=50), nullable=False),
        sa.Column("target_duration", sa.Integer(), nullable=False),
        sa.Column("video_mode", sa.String(length=64), nullable=False),
        sa.Column("video_type", sa.String(length=64), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "RUNNING", "PAUSED", "COMPLETED", "FAILED", name="projectstatus"),
            nullable=False,
        ),
        sa.Column("current_stage", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cover_emoji", sa.String(length=16), nullable=True),
        sa.Column("cover_generation_attempted", sa.Boolean(), nullable=False),
        sa.Column("cover_generated_at", sa.DateTime(), nullable=True),
        sa.Column("output_dir", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "provider_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "provider_type",
            sa.Enum("LLM", "SEARCH", "AUDIO", "IMAGE", "VIDEO", name="providertype"),
            nullable=False,
        ),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reference_library_import_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELED",
                name="referenceimportjobstatus",
            ),
            nullable=False,
        ),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("canceled_count", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_requested_by", sa.String(length=64), nullable=True),
        sa.Column("terminal_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reference_library_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("can_speak", sa.Boolean(), nullable=False),
        sa.Column("setting", sa.Text(), nullable=True),
        sa.Column("appearance_description", sa.Text(), nullable=True),
        sa.Column("voice_audio_provider", sa.String(length=32), nullable=True),
        sa.Column("voice_name", sa.String(length=255), nullable=True),
        sa.Column("voice_speed", sa.Float(), nullable=True),
        sa.Column("voice_wan2gp_preset", sa.String(length=128), nullable=True),
        sa.Column("voice_wan2gp_alt_prompt", sa.Text(), nullable=True),
        sa.Column("voice_wan2gp_audio_guide", sa.Text(), nullable=True),
        sa.Column("voice_wan2gp_temperature", sa.Float(), nullable=True),
        sa.Column("voice_wan2gp_top_k", sa.Integer(), nullable=True),
        sa.Column("voice_wan2gp_seed", sa.Integer(), nullable=True),
        sa.Column("image_file_path", sa.String(length=500), nullable=True),
        sa.Column("image_updated_at", sa.Integer(), nullable=True),
        sa.Column(
            "source_channel",
            sa.Enum("MANUAL", "IMAGE_BATCH", name="referencesourcechannel"),
            nullable=True,
        ),
        sa.Column("source_file_name", sa.String(length=255), nullable=True),
        sa.Column(
            "name_status",
            sa.Enum(
                "pending", "running", "ready", "failed", "canceled", name="referenceitemfieldstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "appearance_status",
            sa.Enum(
                "pending", "running", "ready", "failed", "canceled", name="referenceitemfieldstatus"
            ),
            nullable=False,
        ),
        sa.Column("processing_stage", sa.String(length=64), nullable=True),
        sa.Column("processing_message", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "text_library_import_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", "CANCELED", name="textimportjobstatus"
            ),
            nullable=False,
        ),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("canceled_count", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_requested_by", sa.String(length=64), nullable=True),
        sa.Column("terminal_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "text_library_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "source_channel",
            sa.Enum(
                "COPY", "FILE", "WEB", "XIAOHONGSHU", "DOUYIN", "KUAISHOU", name="textsourcechannel"
            ),
            nullable=False,
        ),
        sa.Column(
            "title_status",
            sa.Enum(
                "pending", "running", "ready", "failed", "canceled", name="textitemfieldstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "content_status",
            sa.Enum(
                "pending", "running", "ready", "failed", "canceled", name="textitemfieldstatus"
            ),
            nullable=False,
        ),
        sa.Column("processing_stage", sa.String(length=64), nullable=True),
        sa.Column("processing_message", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("source_file_name", sa.String(length=255), nullable=True),
        sa.Column("source_post_id", sa.String(length=128), nullable=True),
        sa.Column("source_post_updated_at", sa.String(length=128), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_text_library_items_source_post_id"),
        "text_library_items",
        ["source_post_id"],
        unique=False,
    )
    op.create_table(
        "text_library_post_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "source_channel",
            sa.Enum(
                "COPY", "FILE", "WEB", "XIAOHONGSHU", "DOUYIN", "KUAISHOU", name="textsourcechannel"
            ),
            nullable=False,
        ),
        sa.Column("post_id", sa.String(length=128), nullable=False),
        sa.Column("post_updated_at", sa.String(length=128), nullable=True),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("media_kind", sa.String(length=32), nullable=True),
        sa.Column("media_url", sa.String(length=2000), nullable=True),
        sa.Column("title_text", sa.Text(), nullable=True),
        sa.Column("note_text", sa.Text(), nullable=True),
        sa.Column("transcript_text", sa.Text(), nullable=True),
        sa.Column("combined_content", sa.Text(), nullable=False),
        sa.Column("generated_title", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_channel", "post_id", name="uq_text_library_post_cache_channel_post_id"
        ),
    )
    op.create_index(
        op.f("ix_text_library_post_cache_post_id"),
        "text_library_post_cache",
        ["post_id"],
        unique=False,
    )
    op.create_table(
        "voice_library_import_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", "CANCELED", name="voiceimportjobstatus"
            ),
            nullable=False,
        ),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("canceled_count", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_requested_by", sa.String(length=64), nullable=True),
        sa.Column("terminal_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "voice_library_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("reference_text", sa.Text(), nullable=True),
        sa.Column("audio_file_path", sa.String(length=500), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("builtin_key", sa.String(length=255), nullable=True),
        sa.Column(
            "source_channel",
            sa.Enum(
                "AUDIO_WITH_TEXT", "AUDIO_FILE", "VIDEO_LINK", "BUILTIN", name="voicesourcechannel"
            ),
            nullable=True,
        ),
        sa.Column("auto_parse_text", sa.Boolean(), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("source_file_name", sa.String(length=255), nullable=True),
        sa.Column("source_post_id", sa.String(length=128), nullable=True),
        sa.Column("source_post_updated_at", sa.String(length=128), nullable=True),
        sa.Column("clip_start_requested_sec", sa.Float(), nullable=True),
        sa.Column("clip_end_requested_sec", sa.Float(), nullable=True),
        sa.Column("clip_start_actual_sec", sa.Float(), nullable=True),
        sa.Column("clip_end_actual_sec", sa.Float(), nullable=True),
        sa.Column(
            "name_status",
            sa.Enum(
                "pending", "running", "ready", "failed", "canceled", name="voiceitemfieldstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "reference_text_status",
            sa.Enum(
                "pending", "running", "ready", "failed", "canceled", name="voiceitemfieldstatus"
            ),
            nullable=False,
        ),
        sa.Column("processing_stage", sa.String(length=64), nullable=True),
        sa.Column("processing_message", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("builtin_key"),
    )
    op.create_index(
        op.f("ix_voice_library_items_source_post_id"),
        "voice_library_items",
        ["source_post_id"],
        unique=False,
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum(
                "COLLECTED_INFO",
                "CONTENT",
                "SUBTITLE",
                "AUDIO",
                "REFERENCE_IMAGE",
                "FRAME_IMAGE",
                "FINAL_VIDEO",
                name="assettype",
            ),
            nullable=False,
        ),
        sa.Column("shot_index", sa.Integer(), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("json_content", sa.JSON(), nullable=True),
        sa.Column("asset_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="pipelinerunstatus"),
            nullable=False,
        ),
        sa.Column(
            "from_stage",
            sa.Enum(
                "RESEARCH",
                "CONTENT",
                "STORYBOARD",
                "AUDIO",
                "SUBTITLE",
                "REFERENCE",
                "FIRST_FRAME_DESC",
                "FRAME",
                "VIDEO",
                "COMPOSE",
                name="stagetype",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_stage",
            sa.Enum(
                "RESEARCH",
                "CONTENT",
                "STORYBOARD",
                "AUDIO",
                "SUBTITLE",
                "REFERENCE",
                "FIRST_FRAME_DESC",
                "FRAME",
                "VIDEO",
                "COMPOSE",
                name="stagetype",
            ),
            nullable=True,
        ),
        sa.Column(
            "current_stage",
            sa.Enum(
                "RESEARCH",
                "CONTENT",
                "STORYBOARD",
                "AUDIO",
                "SUBTITLE",
                "REFERENCE",
                "FIRST_FRAME_DESC",
                "FRAME",
                "VIDEO",
                "COMPOSE",
                name="stagetype",
            ),
            nullable=True,
        ),
        sa.Column("worker_name", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_runs_project_id"), "pipeline_runs", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_pipeline_runs_status"), "pipeline_runs", ["status"], unique=False)
    op.create_table(
        "reference_library_import_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("source_file_name", sa.String(length=255), nullable=False),
        sa.Column("input_name", sa.String(length=255), nullable=True),
        sa.Column("generate_description", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELED",
                name="referenceimporttaskstatus",
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("stage_message", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_reason", sa.String(length=64), nullable=True),
        sa.Column("retry_of_task_id", sa.Integer(), nullable=True),
        sa.Column("retry_no", sa.Integer(), nullable=False),
        sa.Column("reference_library_item_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["reference_library_import_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_library_item_id"],
            ["reference_library_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reference_library_import_tasks_job_id"),
        "reference_library_import_tasks",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reference_library_import_tasks_reference_library_item_id"),
        "reference_library_import_tasks",
        ["reference_library_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reference_library_import_tasks_retry_of_task_id"),
        "reference_library_import_tasks",
        ["retry_of_task_id"],
        unique=False,
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("SEARCH", "DEEP_RESEARCH", "TEXT", name="sourcetype"), nullable=False
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stage_executions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "stage_type",
            sa.Enum(
                "RESEARCH",
                "CONTENT",
                "STORYBOARD",
                "AUDIO",
                "SUBTITLE",
                "REFERENCE",
                "FIRST_FRAME_DESC",
                "FRAME",
                "VIDEO",
                "COMPOSE",
                name="stagetype",
            ),
            nullable=False,
        ),
        sa.Column("stage_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", "SKIPPED", name="stagestatus"),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=True),
        sa.Column("output_data", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("last_item_complete", sa.Integer(), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=True),
        sa.Column("completed_items", sa.Integer(), nullable=True),
        sa.Column("skipped_items", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "text_library_import_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=False),
        sa.Column(
            "source_channel",
            sa.Enum(
                "COPY", "FILE", "WEB", "XIAOHONGSHU", "DOUYIN", "KUAISHOU", name="textsourcechannel"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", "CANCELED", name="textimporttaskstatus"
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("stage_message", sa.Text(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_reason", sa.String(length=64), nullable=True),
        sa.Column("retry_of_task_id", sa.Integer(), nullable=True),
        sa.Column("retry_no", sa.Integer(), nullable=False),
        sa.Column("text_library_item_id", sa.Integer(), nullable=True),
        sa.Column("source_post_id", sa.String(length=128), nullable=True),
        sa.Column("source_post_updated_at", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["text_library_import_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["text_library_item_id"],
            ["text_library_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_text_library_import_tasks_job_id"),
        "text_library_import_tasks",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_text_library_import_tasks_retry_of_task_id"),
        "text_library_import_tasks",
        ["retry_of_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_text_library_import_tasks_source_post_id"),
        "text_library_import_tasks",
        ["source_post_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_text_library_import_tasks_text_library_item_id"),
        "text_library_import_tasks",
        ["text_library_item_id"],
        unique=False,
    )
    op.create_table(
        "voice_library_import_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column(
            "source_channel",
            sa.Enum(
                "AUDIO_WITH_TEXT", "AUDIO_FILE", "VIDEO_LINK", "BUILTIN", name="voicesourcechannel"
            ),
            nullable=False,
        ),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("source_file_name", sa.String(length=255), nullable=True),
        sa.Column("auto_parse_text", sa.Boolean(), nullable=False),
        sa.Column("clip_start_requested_sec", sa.Float(), nullable=True),
        sa.Column("clip_end_requested_sec", sa.Float(), nullable=True),
        sa.Column("clip_start_actual_sec", sa.Float(), nullable=True),
        sa.Column("clip_end_actual_sec", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELED",
                name="voiceimporttaskstatus",
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("stage_message", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_reason", sa.String(length=64), nullable=True),
        sa.Column("retry_of_task_id", sa.Integer(), nullable=True),
        sa.Column("retry_no", sa.Integer(), nullable=False),
        sa.Column("voice_library_item_id", sa.Integer(), nullable=True),
        sa.Column("source_post_id", sa.String(length=128), nullable=True),
        sa.Column("source_post_updated_at", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["voice_library_import_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voice_library_item_id"],
            ["voice_library_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_voice_library_import_tasks_job_id"),
        "voice_library_import_tasks",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_voice_library_import_tasks_retry_of_task_id"),
        "voice_library_import_tasks",
        ["retry_of_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_voice_library_import_tasks_source_post_id"),
        "voice_library_import_tasks",
        ["source_post_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_voice_library_import_tasks_voice_library_item_id"),
        "voice_library_import_tasks",
        ["voice_library_item_id"],
        unique=False,
    )
    op.create_table(
        "pipeline_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "stage_type",
            sa.Enum(
                "RESEARCH",
                "CONTENT",
                "STORYBOARD",
                "AUDIO",
                "SUBTITLE",
                "REFERENCE",
                "FIRST_FRAME_DESC",
                "FRAME",
                "VIDEO",
                "COMPOSE",
                name="stagetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "task_kind", sa.Enum("STAGE", "PIPELINE_STAGE", name="pipelinetaskkind"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "SKIPPED",
                name="pipelinetaskstatus",
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("worker_name", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_tasks_project_id"), "pipeline_tasks", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_pipeline_tasks_run_id"), "pipeline_tasks", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_pipeline_tasks_stage_type"), "pipeline_tasks", ["stage_type"], unique=False
    )
    op.create_index(op.f("ix_pipeline_tasks_status"), "pipeline_tasks", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_tasks_status"), table_name="pipeline_tasks")
    op.drop_index(op.f("ix_pipeline_tasks_stage_type"), table_name="pipeline_tasks")
    op.drop_index(op.f("ix_pipeline_tasks_run_id"), table_name="pipeline_tasks")
    op.drop_index(op.f("ix_pipeline_tasks_project_id"), table_name="pipeline_tasks")
    op.drop_table("pipeline_tasks")
    op.drop_index(
        op.f("ix_voice_library_import_tasks_voice_library_item_id"),
        table_name="voice_library_import_tasks",
    )
    op.drop_index(
        op.f("ix_voice_library_import_tasks_source_post_id"),
        table_name="voice_library_import_tasks",
    )
    op.drop_index(
        op.f("ix_voice_library_import_tasks_retry_of_task_id"),
        table_name="voice_library_import_tasks",
    )
    op.drop_index(
        op.f("ix_voice_library_import_tasks_job_id"), table_name="voice_library_import_tasks"
    )
    op.drop_table("voice_library_import_tasks")
    op.drop_index(
        op.f("ix_text_library_import_tasks_text_library_item_id"),
        table_name="text_library_import_tasks",
    )
    op.drop_index(
        op.f("ix_text_library_import_tasks_source_post_id"), table_name="text_library_import_tasks"
    )
    op.drop_index(
        op.f("ix_text_library_import_tasks_retry_of_task_id"),
        table_name="text_library_import_tasks",
    )
    op.drop_index(
        op.f("ix_text_library_import_tasks_job_id"), table_name="text_library_import_tasks"
    )
    op.drop_table("text_library_import_tasks")
    op.drop_table("stage_executions")
    op.drop_table("sources")
    op.drop_index(
        op.f("ix_reference_library_import_tasks_retry_of_task_id"),
        table_name="reference_library_import_tasks",
    )
    op.drop_index(
        op.f("ix_reference_library_import_tasks_reference_library_item_id"),
        table_name="reference_library_import_tasks",
    )
    op.drop_index(
        op.f("ix_reference_library_import_tasks_job_id"),
        table_name="reference_library_import_tasks",
    )
    op.drop_table("reference_library_import_tasks")
    op.drop_index(op.f("ix_pipeline_runs_status"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_project_id"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_table("assets")
    op.drop_index(op.f("ix_voice_library_items_source_post_id"), table_name="voice_library_items")
    op.drop_table("voice_library_items")
    op.drop_table("voice_library_import_jobs")
    op.drop_index(op.f("ix_text_library_post_cache_post_id"), table_name="text_library_post_cache")
    op.drop_table("text_library_post_cache")
    op.drop_index(op.f("ix_text_library_items_source_post_id"), table_name="text_library_items")
    op.drop_table("text_library_items")
    op.drop_table("text_library_import_jobs")
    op.drop_table("reference_library_items")
    op.drop_table("reference_library_import_jobs")
    op.drop_table("provider_configs")
    op.drop_table("projects")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
